apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: cloudcart
  labels:
    app.kubernetes.io/name: order-db
    app.kubernetes.io/part-of: cloudcart
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: order-db
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
