apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: cloudcart
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: cloudcart
data:
  PORT: "8085"
  NODE_ENV: production
