apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: cloudcart
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/part-of: cloudcart
data:
  PORT: "8084"
  NODE_ENV: production
