apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: cloudcart
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: cloudcart
data:
  DB_URL: jdbc:postgresql://order-db:5432/cloudcart_orders
  DB_USERNAME: cloudcart
  PRODUCT_SERVICE_URL: http://product-service:8082
  JPA_DDL_AUTO: update
  SERVER_PORT: "8083"
