apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: cloudcart
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: cloudcart
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: order-service

  ports:
    - name: http
      port: 8083
      targetPort: http
