apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: cloudcart
  labels:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/part-of: cloudcart
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: product-service

  ports:
    - name: http
      port: 8082
      targetPort: http
