spring:
  application:
    name: order-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cloudcart_orders}
    username: ${DB_USERNAME:cloudcart}
    password: ${DB_PASSWORD:cloudcart}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

app:
  product-service:
    base-url: ${PRODUCT_SERVICE_URL:http://localhost:8082}

server:
  port: ${SERVER_PORT:8083}