{{- $root := . }}
{{- range $name, $application := .Values.applications }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-config
  namespace: {{ include "cloudcart.namespace" $root }}
  labels:
    {{- include "cloudcart.selectorLabels" (dict "root" $root "component" $name) | nindent 4 }}
data:
  {{- range $key, $value := $application.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
