{{- $root := . }}
{{- range $name, $database := .Values.databases }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ include "cloudcart.namespace" $root }}
  labels:
    {{- include "cloudcart.selectorLabels" (dict "root" $root "component" $name) | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "cloudcart.selectorLabels" (dict "root" $root "component" $name) | nindent 4 }}
  ports:
    - name: postgres
      port: {{ $root.Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
{{- end }}
