apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: cloudcart
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/part-of: cloudcart
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payment-service
  ports:
    - name: http
      port: 8084
      targetPort: http
